# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-ast
        name: Check python ast (with Python 2.7)
        language_version: python2.7
        stages: [manual]
        files: '^tools/build_utils/.*\.py'
    -   id: check-ast
        name: Check python ast (with Python 3)
        language_version: python3
        stages: [manual]
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black
        exclude: >-
          (?x)^(
            exts/.*|
            tools/prettify/fprettify/.|
            tools/build_utils/fypp|
          )$
-   repo: local
    hooks:
    -   id: doxify
        name: Run doxify
        entry: ./tools/doxify/doxify.sh
        language: script
        files: '^src/.*\.(F|f90)$'
    -   id: prettify
        name: Run prettify
        entry: ./tools/prettify/prettify.py
        language: script
        files: '^src/.*\.(F|f90)$'
        exclude: >-
          (?x)^(
            src/base/base_uses.f90|
            src/common/util.F|
          )$
    -   id: analyze_src
        name: Run analyze_src
        entry: ./tools/conventions/analyze_src.py --fail --suppressions ./tools/conventions/conventions.supp
        language: script
        files: '^src/.*\.(F|fypp|c|cu|cpp|h|hpp)$'
    -   id: regen_data
        name: Regenerate checked-in data files
        entry: make --always-make data
        language: system
        files: 'data/*'
        pass_filenames: false
